//
//  RequisitosInteractor.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequisitosBusinessLogic
{
  func doSomething(request: Requisitos.Something.Request)
}

protocol RequisitosDataStore
{
  //var name: String { get set }
}

class RequisitosInteractor: RequisitosBusinessLogic, RequisitosDataStore
{
  var presenter: RequisitosPresentationLogic?
  var worker: RequisitosWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Requisitos.Something.Request)
  {
    worker = RequisitosWorker()
    worker?.doSomeWork()
    
    let response = Requisitos.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
