//
//  ColibriPresenter.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColibriPresentationLogic
{
    func presentTableData(data:ColibriModel.Verificentros?)
}

class ColibriPresenter: ColibriPresentationLogic
{
    
    
  weak var viewController: ColibriDisplayLogic?
  
  // MARK: Do something
  
    func presentTableData(data: ColibriModel.Verificentros?) {
        self.viewController?.displayTableData(data: data)
    }
}
