//
//  ColibriModels.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum ColibriModel {
// MARK: - Verificentros
struct Verificentros: Codable {
    var Table: [Table1]?
}

// MARK: - Table1
struct Table1: Codable {
    var Id, Nombre: String?
    var Link: String?
    var Tipo: String?
    var Localidad: String?
    var Especialidad: String?
}
}
