//
//  ColibriPresenter.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColibriPresentationLogic
{
  func presentSomething(response: Colibri.Something.Response)
}

class ColibriPresenter: ColibriPresentationLogic
{
  weak var viewController: ColibriDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Colibri.Something.Response)
  {
    let viewModel = Colibri.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
