//
//  ColibriInteractor.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColibriBusinessLogic
{
  func doSomething(request: Colibri.Something.Request)
}

protocol ColibriDataStore
{
  //var name: String { get set }
}

class ColibriInteractor: ColibriBusinessLogic, ColibriDataStore
{
  var presenter: ColibriPresentationLogic?
  var worker: ColibriWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Colibri.Something.Request)
  {
    worker = ColibriWorker()
    worker?.doSomeWork()
    
    let response = Colibri.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
