//
//  ConfigInteractor.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfigBusinessLogic
{
  func doSomething(request: Config.Something.Request)
}

protocol ConfigDataStore
{
  //var name: String { get set }
}

class ConfigInteractor: ConfigBusinessLogic, ConfigDataStore
{
  var presenter: ConfigPresentationLogic?
  var worker: ConfigWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Config.Something.Request)
  {
    worker = ConfigWorker()
    worker?.doSomeWork()
    
    let response = Config.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
