//
//  ConfigPresenter.swift
//  VeriApp
//
//  Created by Emilio on 11/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfigPresentationLogic
{
  func presentSomething(response: Config.Something.Response)
}

class ConfigPresenter: ConfigPresentationLogic
{
  weak var viewController: ConfigDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Config.Something.Response)
  {
    let viewModel = Config.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
